import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAddressBook,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faBars,
  faBed,
  faBuilding,
  faCancel,
  faCar,
  faCashRegister,
  faCheckCircle,
  faCircle,
  faCircleXmark,
  faCogs,
  faDoorOpen,
  faEdit,
  faEllipsisStroke,
  faEye,
  faEyeSlash,
  faFileChartPie,
  faFlaskVial,
  faGlobeAmericas,
  faHandHoldingDollar,
  faHome,
  faKeyboard,
  faPlus,
  faPrint,
  faScanner,
  faSignIn,
  faSignOut,
  faSpinner,
  faTimesCircle,
  faTrash,
  faUserHardHat,
  faUserNurse,
  faUsers,
  faAbacus,
  faReceipt,
  faIdCard,
} from "@fortawesome/pro-light-svg-icons";

const loadIcons = (): void => {
  library.add(faPlus);
  library.add(faBars);
  library.add(faAngleRight);
  library.add(faAngleLeft);
  library.add(faAngleDown);
  library.add(faGlobeAmericas);
  library.add(faUsers);
  library.add(faCogs);
  library.add(faSignOut);
  library.add(faHome);
  library.add(faUserNurse);
  library.add(faSpinner);
  library.add(faTrash);
  library.add(faEdit);
  library.add(faDoorOpen);
  library.add(faSignIn);
  library.add(faCheckCircle);
  library.add(faTimesCircle);
  library.add(faUserHardHat);
  library.add(faAddressBook);
  library.add(faScanner);
  library.add(faKeyboard);
  library.add(faBuilding);
  library.add(faEye);
  library.add(faBed);
  library.add(faCar);
  library.add(faCashRegister);
  library.add(faCircleXmark);
  library.add(faHandHoldingDollar);
  library.add(faEllipsisStroke);
  library.add(faCancel);
  library.add(faFileChartPie);
  library.add(faFlaskVial);
  library.add(faPrint);
  library.add(faCircle);
  library.add(faAbacus);
  library.add(faReceipt);
  library.add(faIdCard);
  library.add(faEyeSlash);
};

export default loadIcons;
